### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by CaptainAm69** [PsiCodes/KtxPy#1]
Hi, The program is extremely beautiful and practical and has high efficiency, but is it possible to install and import libraries in it? Please tell me as soon as possible❤
Edit: I see that you haven't added the user interface libraries feature, however I think it is possible to manually import a library, is that so?

**Comment by psi314** [comment]
Hi, first of all, thanks for all the compliments, but for now it is not possible to import libraries into it as it is very time consuming to cross compile libraries for Android; surely, in the future, I will add missing libraries, but for now it is not possible. If you really want to use a particular library, you can cross compile it yourself; reach out to me if you need any help.

**Comment by CaptainAm69** [comment]
> Hi, first of all, thanks for all the compliments, but for now it is not possible to import libraries into it as it is very time consuming to cross compile libraries for Android; surely, in the future, I will add missing libraries, but for now it is not possible. If you really want to use a particular library, you can cross compile it yourself; reach out to me if you need any help.

Wow! Hello, have a good time!  Thanks for your quick reply!  I have no experience in cross compiling but with your help I will try my best to import some libraries.

**Comment by CaptainAm69** [comment]
So, what should I do?

**Comment by psi314** [comment]
You can use simple modules like requests, beautiful soup, etc. by just downloading their source and putting modules in the site-package directory using terminal. but if your module is GUI-based or requires any additional program, you will require the Android NDK for cross-compiling that module. You can search for tutorials online.

**Comment by CaptainAm69** [comment]
> You can use simple modules like requests, beautiful soup, etc. by just downloading their source and putting modules in the site-package directory using terminal. but if your module is GUI-based or requires any additional program, you will require the Android NDK for cross-compiling that module. You can search for tutorials online.

Thank you, you're best!😃

**Comment by psi314** [comment]
Thanks for the compliment.
