### ISSUE TITLE
Feature request: Improve UI using Material3

### ISSUE THREAD

**Issue by Lohita9** [PsiCodes/KtxPy#12]
![unnamed (2).png](https://github.com/PsiCodes/KtxPy/assets/123667347/c441eb80-3d01-4155-ad4c-001541c8349d)

![unnamed (1).png](https://github.com/PsiCodes/KtxPy/assets/123667347/e83a947d-8aae-45fd-9876-5e8c79225f22)

![unnamed.png](https://github.com/PsiCodes/KtxPy/assets/123667347/7cf2b05b-45a8-4e81-bec1-7a57c0461fe5)

Check out these images of the CodeAssist app. Modify your Ktxpy app to enhance the UI, incorporating Material3. For example, in the CodeAssist app, the run button is located in the top app bar—please make a similar adjustment in the Ktxpy app. Additionally, consider adding a build logs function to the Ktxpy app, similar to the one in the CodeAssist app.
Use top app bars instead of MaterialToolbar for improved clarity and readability.
And 
set 
```
	<item name="android:navigationBarColor">@android:color/transparent</item>
	 <!-- set to transparent if your app is drawing behind the status bar. --> -->
	<item name="android:statusBarColor">@android:color/transparent</item>
	 <!-- set for a light status bar with dark content. --> -->
	<item name="android:windowLightStatusBar">true</item>
	<item name="android:windowLightNavigationBar">true</item>
```
Implement support for both light and dark modes in the app. Preferably, utilize "Theme.Material3.Light.NoActionBar" in values/themes.xml for light mode and "Theme.Material3.Dark.NoActionBar" in values-night/themes.xml for dark mode.

**Comment by psi314** [comment]
Sure i will  try to add these features

**Comment by Lohita9** [comment]
@PsiCodes I noticed that the issue was marked as completed. However, I couldn't find corresponding changes pushed to the KtxPy repository. Could you please provide some clarification on this matter?

**Comment by psi314** [comment]
I have marked these points, and I will add them in a later update.
