### ISSUE TITLE
Request for Java Rewrite

### ISSUE THREAD

**Issue by Lohita9** [PsiCodes/KtxPy#14]
Hi @PsiCodes,

I've been following the development of your "KtxPy" repository, and I find it interesting. However, I believe it could be beneficial to a wider audience if it were written in Java, as it's a language that more people are familiar with.

I kindly request if you could consider rewriting the codebase in Java. Additionally, it would be great if you could provide comprehensive documentation to help users understand the project better.

**Comment by psi314** [comment]
It is not possible as most of the ui is built with compose.
