### ISSUE TITLE
Add a margin around line number

### ISSUE THREAD

**Issue by RaSan147** [PsiCodes/KtxPy#19]
The screen protector guys played dirty amd game me cornered black (about 2px) protector

When i try to check the line number, its mostly under there (its wayyy to much on the edge)

Please add a minimum margin on the left.

**Comment by psi314** [comment]
You can customize the source code according to your needs and make changes according to them. I cannot add this as it will look odd for people with normal screens/protectors.

**Comment by RaSan147** [comment]
Well its the basic, even vs code and all other editors have minimum margin, this editor has like 0 sadly...
