### ISSUE TITLE
[feature]: set file path

### ISSUE THREAD

**Issue by hasanelfalakiy** [PsiCodes/KtxPy#3]
please add feature set file save path when creating new file, i suggest in the dialog while creating new file.
so in the create new file dialog, there is a file title then below it is edit text to set the file storage path, just make the default /storage/emulated/0/KtxPyProjects/
for the menu for creating a folder, I think we can use the terminal for a while

**Comment by psi314** [comment]
Ok I will soon add support for this. 
Thanks for Suggestion

**Comment by hasanelfalakiy** [comment]
my pleasure
