### ISSUE TITLE
[repair]: status pointers and toolbars

### ISSUE THREAD

**Issue by hasanelfalakiy** [PsiCodes/KtxPy#4]
suggestions to fix the pointer color of the hostname/terminal directory to green and add a toolbar like the original termux because this feature is very important, as I marked
![IMG_20230625_133831](https://github.com/PsiCodes/KtxPy/assets/96150715/a30a0dcf-4eda-48df-9b76-34c791b6be3b)

**Comment by psi314** [comment]
As I have modified the original version of Jackpal's android terminal u can still use special keys using volume button.
but i will try to implement toolbar in next update
