### ISSUE TITLE
The application does not open

### ISSUE THREAD

**Issue by kaicsm** [PsiCodes/KtxPy#6]
On device LG K41S arm.
Version 1.1.0.
The app just won't open, please fix this

**Comment by psi314** [comment]
Could you please provide the logs?

**Comment by Sohil876** [comment]
> Could you please provide the logs?

Same here, his device is probably armv7 like mine, afaik this is arm64 only atm?

**Comment by kaicsm** [comment]
Look:

https://github.com/PsiCodes/KtxPy/assets/68879185/786dd849-6adb-4d77-a4b3-3fb6e33b577e

**Comment by psi314** [comment]
I think problem is with un7zip. If you can kindly provide logs via logcat.

**Comment by kaicsm** [comment]
> I think problem is with un7zip. If you can kindly provide logs via logcat.

My phone is not rooted, so I can't see the logs with logcat, try adding a CrashHandler

**Comment by kaicsm** [comment]
I don't know if this is on purpose, but it's really missing some .so:

https://github.com/PsiCodes/KtxPy/assets/68879185/a89fbc1c-d3d4-408f-82f1-4921f448a2e6

**Comment by psi314** [comment]
If your arch is armeabi-v7, it will not work, as Ktxpy only supports arm64 and x86_64. I am working on adding support for armv7.

**Comment by psi314** [comment]
@kaicsm arm32 support is added you may install it now

**Comment by kaicsm** [comment]
Thank you very much :)
