### ISSUE TITLE
Support for armv7?

### ISSUE THREAD

**Issue by Sohil876** [PsiCodes/KtxPy#7]
This is arm64 only atm? Is armv7 support planned? Would love to use this on my old device.

**Comment by psi314** [comment]
As of now , armeabi-v7 isn't supported, as I don't have armv7 device for testing.

**Comment by Sohil876** [comment]
> As of now , armeabi-v7 isn't supported, as I don't have armv7 device for testing.

Users can test it i can too so maybe give it a go? You can also keep that on a new branch untill its stable, I tried building for [armv7](https://github.com/miscdevstuff/KtxPy/commit/fd8fd69d480f25c7f22feaa6282a3bb27539bdf8) but it crashes due to something can you take a look if its something unrelated to armv7 or my build?
Here's log: https://pastebin.com/REAJvT3V

Also checkout [this issue on un7zip](https://github.com/hzy3774/AndroidUn7zip/issues/31) maybe thats what happening? Then the other opened issue atm is probably because of this too.

**Comment by psi314** [comment]
I think you are right crash is due to un7zip. Additionally, be sure to cross-compile the Python executable if you are building for Armv7. 
If possible, I would try to provide Armv7 support as soon as possible.

**Comment by Sohil876** [comment]
> I think you are right crash is due to un7zip. Additionally, be sure to cross-compile the Python executable if you are building for Armv7. If possible, I would try to provide Armv7 support as soon as possible.

I have, tho i dont get pip in usr/bin/ even when i built it using --with-ensurepip flag.
Also i can confirm the crash is due to un7zip, i replaced build.7z with a dummy one 1MB file and it didnt crash.

![Screenshot_20230703-151301_KtxPy](https://github.com/PsiCodes/KtxPy/assets/3389469/bef44d0b-561c-41c0-abd7-519669dfffc8)

**Comment by psi314** [comment]
@Sohil876 If you have cross-compiled python yourself, you can use this python [file](https://bootstrap.pypa.io/get-pip.py) for getting pip. maybe I should replace un7zip with some other library or try to optimise it,thanks for confirming the issue.

**Comment by psi314** [comment]
@Sohil876 If you want, you can help me with testing. It will be really helpful.

**Comment by Sohil876** [comment]
> @Sohil876 If you want, you can help me with testing. It will be really helpful.

Sure.

**Comment by psi314** [comment]
@Sohil876 If you are comfortable with Telegram, you can contact me on Telegram (username: @PsiCodes).

**Comment by psi314** [comment]
arm32 support is added
