### ISSUE TITLE
Editor bug when it has few lines

### ISSUE THREAD

**Issue by kaicsm** [PsiCodes/KtxPy#8]
![Screenshot_20230712-125932.png](https://github.com/PsiCodes/KtxPy/assets/68879185/94021016-a882-4a74-817d-700ed668c26f)

This bug happens when the number of lines doesn't keep up with the screen size

I am using armv7 version

**Comment by psi314** [comment]
Sorry that issue is due to latest version of sora code editor. I am working on this

**Comment by psi314** [comment]
@kaicsm this issue has been fixed [here](https://github.com/PsiCodes/KtxPy/commit/5d02c55593c66d1979d416a2935427947b20399b)
