### ISSUE TITLE
my pullrequest

### ISSUE THREAD

**Issue by hasanelfalakiy** [PsiCodes/KtxPy#9]
bro, why are all my pullrequests I've ever sent lost in this release?

**Comment by psi314** [comment]
Sorry, but due to some issues, I had to force push. You are still shown as a contributor in the repo.

**Comment by hasanelfalakiy** [comment]
> Sorry, but due to some issues, I had to force push. You are still shown as a contributor in the repo.

ok no problem, looks like my repository still has changes, I'll have a look

**Comment by hasanelfalakiy** [comment]
I already make pullrequest it, let's see
